### ISSUE TITLE
unknown error when trying to register as a new user

### ISSUE THREAD

**Issue by KhaaL** [Librum-Reader/Librum#112] opened 2023-12-30 18:40 UTC
**Describe the bug**
I downloaded the app as a flatpak, but cannot register a new user after filling out all fields. I get a "An unknown error occured"

**To Reproduce**
1. Install flatpak app.
2. Click on register new user
3. fill out all fields.

**Expected behavior**
Be able to use the app.

**Desktop (please complete the following information):**
 - OS: Feodra 39 (x86_64)

**Comment by DavidLazarescu** [comment] 2023-12-30 18:44
Thank you for reporting this issue. A very recent change seems to have caused the api to fail which leads to this error. I have just pushed a fix that should bring the server back to a decent state.

**Comment by DavidLazarescu** [comment] 2023-12-30 18:52
The problem is now fixed.

**Closed by DavidLazarescu** 2023-12-30 18:52 UTC

**Comment by KhaaL** [comment] 2023-12-30 21:28
That was fast 😄  

Thank you, and happy new year 🎆
