### ISSUE TITLE
[MacOS, UI/UX] - Change cursor type on hover for active elements like buttons, dropdowns, radio buttons

### ISSUE THREAD

**Issue by MrOnlineCoder** [Librum-Reader/Librum#106] opened 2023-12-21 22:17 UTC
**Describe the bug**
On MacOS (at least), hovering (moving mouse over) buttons like Login, Add book, or any Settings control does not change cursor from default to "pointer" style, which is usually expected from such controls to provide visual feedback to user, emphasizing that the element of layout he is pointing is clickable.

**To Reproduce**
1. Hover over any clickable button or control

**Expected behavior**
Mouse cursor is switched to "hand pointer", instead of being left as regular dark arrow.

**Desktop (please complete the following information):**
 - OS: MacOS 13.5
 - Version 0.11.0 (build from source)

**Comment by DavidLazarescu** [comment] 2023-12-22 10:55
This was done on purpose and is not a bug, but I understand that it might be nicer feedback-wise to change the cursor. I will be working on a fix for it soon.

**Comment by DavidLazarescu** [comment] 2024-01-03 08:49
This was fixed by e45754bec3fb2099623418300208792704d3fb02

**Closed by DavidLazarescu** 2024-01-03 08:49 UTC
