### ISSUE TITLE
Blurry text and images

### ISSUE THREAD

**Issue by fuadalew** [Librum-Reader/Librum#41] opened 2023-09-09 22:22 UTC
Would love to use this software for as my go-to textbook ereader, but the thing is that everything is blurry. Have no idea what the problem is, and this problem is for all of my textbooks. Would love some insight on this, images are attached below. (First is Librruim, 2nd 
![librum_XUT7tRyWgn](https://github.com/Librum-Reader/Librum/assets/122941128/f391b0c5-ec3c-4cbb-8983-51f8ed844b1f)
![b8mFoRoR9w](https://github.com/Librum-Reader/Librum/assets/122941128/041397fb-9c53-4243-94b6-6ef38e202f92)
one is Firefox's PDF viewer)

**Comment by DavidLazarescu** [comment] 2023-09-09 22:24
Hey, thanks for reporting the issue. Are you running Librum on windows? Also, does it help when you zoom in?

**Comment by fuadalew** [comment] 2023-09-10 21:14
I am running on Windows, and it does help a bit when I zoom in, but I like seeing the whole page.

**Comment by DavidLazarescu** [comment] 2023-09-11 05:21
Ok this seems to be an issue with Librum on windows. I got a similar report for windows before. I'll look into why this might be happening.

**Comment by francescofragomeli** [comment] 2023-09-17 09:54
Hey got the same issue here

**Comment by adch99** [comment] 2023-09-17 18:50
I have the same issue running Librum. This is not limited to Windows.
OS: Arch Linux
Package Type: Flatpak
Version: 0.7.0
Qt Version: 6.5.2

**Comment by DavidLazarescu** [comment] 2023-09-17 19:24
That is weird, I never ran into this kind of problem. I am also running on arch linux via the flatpak version.

Are you using NVIDIA or AMD?

**Comment by adch99** [comment] 2023-09-17 19:26
Neither Nvidia nor AMD. I am on Intel Integrated Graphics which should be supported very well. I am on Wayland though. Maybe this is a HiDPI problem? The rest of the UI scaling is fine though. Only the PDF content is blurred.

**Comment by DavidLazarescu** [comment] 2023-09-17 19:35
I have never tested it on wayland, do you maybe have a way run Librum on X11?

Non the less, this does not explain why some people have this issue on Windows.

**Comment by DavidLazarescu** [comment] 2023-09-18 16:19
I am on 1080x1920 as well but I do not run into these errors

**Comment by DavidLazarescu** [comment] 2023-10-05 11:22
Hey, for everyone for you on windows, could it be that you have a screen zoom applied? You can check this by going to Settings -> System -> Display -> Scale

When putting it on e.g. 125% I can replicate the blurry-ness issue.

**Comment by quesada** [comment] 2023-10-27 21:53
Can replicate

**Comment by DavidLazarescu** [comment] 2023-10-28 11:16
> Can confirm it has nothing to do with the OS and it is instead DPI-related: ran Librum in 800x600 and it's not blurry at all, while it it is blurry at my native resolution of 1920x1080.

I am not able to replicate this. I have tried with multiple different screen resolutions and the text is not blurry. The only way in which I manage to replicate it is by scaling the screen to e.g. 125%.

In the first part of the following video I am changing between all kinds of different resolutions which doesn't seem to get the text blurry. At the end, the blurriness is coming from changing the screen scale.

https://github.com/Librum-Reader/Librum/assets/69865187/6e9582fd-aecd-46f9-8890-716b025dc10e

Do the people who run into this problem have a scale applied to their screen?

**Comment by DavidLazarescu** [comment] 2023-10-29 08:51
Ok, I found a fix for this on windows that will be released in the next version. I think that a similar approach should work for linux, but I am not able to replicate the DPI caused blurriness there, so it would be great if someone who runs into this issue on Linux could test it for me.

**Comment by DavidLazarescu** [comment] 2023-11-01 16:41
I have found the cause of the issue and fixed it. It will be in the next release (v.0.10.1)

**Closed by DavidLazarescu** 2023-11-01 16:41 UTC
